[2024-05-12T13:43:26.297+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T13:43:26.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_and_github_integration.extract_data scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T13:43:26.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_and_github_integration.extract_data scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-12T13:43:26.429+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T13:43:26.511+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-05-11 00:00:00+00:00
[2024-05-12T13:43:26.532+0000] {standard_task_runner.py:63} INFO - Started process 175 to run task
[2024-05-12T13:43:26.537+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dvc_and_github_integration', 'extract_data', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/Script.py', '--cfg-path', '/tmp/tmpt993a9lj']
[2024-05-12T13:43:26.540+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_data
[2024-05-12T13:43:26.671+0000] {task_command.py:426} INFO - Running <TaskInstance: dvc_and_github_integration.extract_data scheduled__2024-05-11T00:00:00+00:00 [running]> on host 850c43a7089d
[2024-05-12T13:43:26.877+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dvc_and_github_integration' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-12T13:43:26.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T13:43:26.989+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T13:43:26.990+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Script.py", line 127, in extract_data
    response = requests.get(url)
               ^^^^^^^^
NameError: name 'requests' is not defined
[2024-05-12T13:43:27.032+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dvc_and_github_integration, task_id=extract_data, run_id=scheduled__2024-05-11T00:00:00+00:00, execution_date=20240511T000000, start_date=20240512T134326, end_date=20240512T134327
[2024-05-12T13:43:27.089+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract_data (name 'requests' is not defined; 175)
[2024-05-12T13:43:27.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T13:43:27.182+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T13:43:27.212+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
