[2024-05-12T13:43:33.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T13:43:33.211+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_and_github_integration.extract_data manual__2024-05-12T13:43:14.377114+00:00 [queued]>
[2024-05-12T13:43:33.236+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_and_github_integration.extract_data manual__2024-05-12T13:43:14.377114+00:00 [queued]>
[2024-05-12T13:43:33.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T13:43:33.290+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-05-12 13:43:14.377114+00:00
[2024-05-12T13:43:33.298+0000] {standard_task_runner.py:63} INFO - Started process 184 to run task
[2024-05-12T13:43:33.301+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dvc_and_github_integration', 'extract_data', 'manual__2024-05-12T13:43:14.377114+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Script.py', '--cfg-path', '/tmp/tmpn_pbc569']
[2024-05-12T13:43:33.303+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_data
[2024-05-12T13:43:33.449+0000] {task_command.py:426} INFO - Running <TaskInstance: dvc_and_github_integration.extract_data manual__2024-05-12T13:43:14.377114+00:00 [running]> on host 850c43a7089d
[2024-05-12T13:43:33.658+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dvc_and_github_integration' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T13:43:14.377114+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T13:43:14.377114+00:00'
[2024-05-12T13:43:33.659+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T13:43:33.687+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T13:43:33.689+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Script.py", line 127, in extract_data
    response = requests.get(url)
               ^^^^^^^^
NameError: name 'requests' is not defined
[2024-05-12T13:43:33.729+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dvc_and_github_integration, task_id=extract_data, run_id=manual__2024-05-12T13:43:14.377114+00:00, execution_date=20240512T134314, start_date=20240512T134333, end_date=20240512T134333
[2024-05-12T13:43:33.784+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task extract_data (name 'requests' is not defined; 184)
[2024-05-12T13:43:33.796+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T13:43:33.839+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T13:43:33.870+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
